read_dir: "results/"
ref: "resources/GCA_019453945.1_ASM1945394v1_genomic.fna"
samples: "resources/samples.tsv"

#BWA-MEM2 parameters
bwamem2:
  algtype: "bwtsw" #algorithm to use to create FMindex (default: 'bwtsw' aka Burrows-Wheeler transformation)

